# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  branches:
    include:
      - main

pool:
    name: npvpn-azure-agent

steps:
  - task: Bash@3
    inputs:
        targetType: "inline"
        script: |
            make docker-release
            docker images -a

  - bash: |
        IMAGE_COMMIT="$(make print-COMMIT)"
        IMAGE_VERSION="$(make print-VERSION)"
        echo "##vso[task.setvariable variable=image_commit]$IMAGE_COMMIT"
        echo "##vso[task.setvariable variable=image_version]$IMAGE_VERSION"

  - task: ECRPushImage@1
    inputs:
        awsCredentials: "imprivata-sandbox azure_pipelines_admin"
        regionName: "us-east-1"
        imageSource: "imagename"
        sourceImageName: "puppers"
        sourceImageTag: $(image_commit)
        repositoryName: "puppers"
        pushTag: $(image_commit)
