
trigger:
  branches:
    include:
      - main
pr: none
pool:
  name: "novpn-azure-agents"

variables:
  - name: somevar
    value: "abc123"

stages:
  - stage: 'Build_Artifacts'
    jobs:
      - job: "Build_Artifacts"
        timeoutInMinutes: 90
        steps:
          - task: Bash@3
            displayName: "Install awscli v2"
            inputs:
              targetType: 'inline' # Optional. Options: filePath, inline
              script: |
                bash -c 'curl "https://raw.githubusercontent.com/natemarks/pipeline-scripts/v0.0.39/scripts/install_awscli_v2.sh" | bash -s '
                export PATH=/usr/local/bin:${PATH}
                aws --version
              workingDirectory:  $(Build.SourcesDirectory)
              failOnStderr: false

          - task: Bash@3
            displayName: "Build lambda artifact"
            inputs:
              targetType: 'inline' # Optional. Options: filePath, inline
              script: |
                make lambda_build
              workingDirectory:  $(Build.SourcesDirectory)
              failOnStderr: false

          - task: CopyFiles@2
            displayName: 'Copy to pipeline artifacts staging'
            inputs:
              contents: "create-zendesk-ticket_$(Build.SourceVersion).zip"
              targetFolder: $(Build.ArtifactStagingDirectory)

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifacts'
            inputs:
              pathToPublish: $(Build.ArtifactStagingDirectory)
              artifactName: "drop"

          - task: AmazonWebServices.aws-vsts-tools.AWSShellScript.AWSShellScript@1
            displayName: 'Upload lambda zip to sandbox S3'
            inputs:
              awsCredentials: 'imprivata-sandbox azure_pipelines_admin'
              regionName: 'us-east-1'
              scriptType: inline
              inlineScript: |
                export PATH=/usr/local/bin:$PATH
                aws s3 cp "create-zendesk-ticket_$(Build.SourceVersion).zip" \
                "s3://com.imprivata.709310380790.us-east-1.devops-artifacts/lambda-create-zendesk-ticket/"

          - task: AmazonWebServices.aws-vsts-tools.AWSShellScript.AWSShellScript@1
            displayName: 'Upload lambda zip to platform dev S3'
            inputs:
              awsCredentials: 'i-platform-dev azure_pipelines_admin'
              regionName: 'us-east-1'
              scriptType: inline
              inlineScript: |
                export PATH=/usr/local/bin:$PATH
                aws s3 cp "create-zendesk-ticket_$(Build.SourceVersion).zip" \
                "s3://com.imprivata.151924297945.us-east-1.devops-artifacts/lambda-create-zendesk-ticket/"

          - task: AmazonWebServices.aws-vsts-tools.AWSShellScript.AWSShellScript@1
            displayName: 'Upload lambda zip to cortext ng S3'
            inputs:
              awsCredentials: 'hybrid_production_admin'
              regionName: 'us-east-1'
              scriptType: inline
              inlineScript: |
                export PATH=/usr/local/bin:$PATH
                aws s3 cp "create-zendesk-ticket_$(Build.SourceVersion).zip" \
                "s3://com.imprivata.468716396736.us-east-1.devops-artifacts/lambda-create-zendesk-ticket/"